rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

spring:
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:spring-security;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
